services:
  threadfin:
    build: .
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      - TZ=Pacific/Auckland
      - FFWR_FFMPEG_PATH=/usr/lib/jellyfin-ffmpeg/ffmpeg
      - FFWR_LOGGING_ENABLED=True
      - FFWR_LOG_LEVEL=INFO
      - FFWR_LOG_RETENTION_DAYS=1
      - FFWR_LOG_DIR=/home/threadfin/conf/log
      - FFWR_FFMPEG_LOG_LEVEL=warning
    volumes:
      - /docker/threadfin/config:/home/threadfin/conf
    restart: unless-stopped
