services:
  threadfin:
    build: .
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - /docker/threadfin/config:/home/threadfin/conf
    restart: unless-stopped
