services:
  threadfin:
    build: .
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Pacific/Auckland
      - FFWR_FFMPEG_PATH=/usr/bin/ffmpeg-bin
      - FFWR_LOGGING_ENABLED=True
      - FFWR_LOG_RETENTION_DAYS=1
      - FFWR_LOG_DIR=/home/threadfin/conf/log
      - FFWR_FFMPEG_LOG_LEVEL=warning
      - FFWR_PROCESS_CONTROL=True
      - FFWR_PROCESS_CONTROL_INTERVAL=60
    volumes:
      - /docker/threadfin/config:/home/threadfin/conf
      #- /tmp/threadfin:/tmp/threadfin
    restart: unless-stopped
